name: Lint OpenAPI specification
on:
  - push
  - pull_request
jobs:
  lint:
    name: Lint OpenAPI spec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 17
    - run: npm ci
    - run: npm run lint
